### PR TITLE
fix: overlapping `Polygon` cutting & color/translucency mixing

### LINKED ISSUE #1898: [BUG] Overlapping `Polygon`s with same colors cause cutting
### What is the bug?

If you have a polygon with one or more holes and another polygon of the same colour is placed inside it, then the second polygon will get rendered as a hole instead of as a filled polygon.

If the polygons have labels, then they are rendered correctly when the labels are rendered. But rendered incorrectly when the labels are not displayed (e.g. when zoomed out)

If the useAltRendering property is set then the polygons will be rendered correctly.

**Expected output:**
Screenshot 2024-05-30 113709

**Actual output:**
Screenshot 2024-05-30 113736

### How can we reproduce it?

The following code can be used to reproduce the issue:

```dart

          FlutterMap(
            options: const MapOptions(
              initialCenter: LatLng(61.858, 0.943),
              initialZoom: 13,
            ),
            children: [
              PolygonLayer(
                polygons: [
                  Polygon(
                      points: const [
                        LatLng(61.861042, 0.946502),
                        LatLng(61.861458, 0.949468),
                        LatLng(61.861427, 0.949626),
                        LatLng(61.859015, 0.951513),
                        LatLng(61.858129, 0.952652)
                      ],
                      holePointsList: [],
                      color: Colors.lightGreen.withOpacity(0.5),
                      borderColor: Colors.lightGreen,
                      borderStrokeWidth: 1),
                  Polygon(
                      points: const [
                        LatLng(61.861042, 0.946502),
                        LatLng(61.861458, 0.949468),
                        LatLng(61.861427, 0.949626),
                        LatLng(61.859015, 0.951513),
                        LatLng(61.858129, 0.952652),
                        LatLng(61.857633, 0.953214),
                        LatLng(61.855842, 0.954683),
                        LatLng(61.855769, 0.954692),
                        LatLng(61.855679, 0.954565),
                        LatLng(61.855417, 0.953926),
                        LatLng(61.855268, 0.953431),
                        LatLng(61.855173, 0.952443),
                        LatLng(61.855161, 0.951147),
                        LatLng(61.855222, 0.950822),
                        LatLng(61.855928, 0.948422),
                        LatLng(61.856365, 0.946638),
                        LatLng(61.856456, 0.946586),
                        LatLng(61.856787, 0.946656),
                        LatLng(61.857578, 0.946675),
                        LatLng(61.859338, 0.946453),
                        LatLng(61.861042, 0.946502)
                      ],
                      holePointsList: const [
                        [
                          LatLng(61.858881, 0.947234),
                          LatLng(61.858728, 0.947126),
                          LatLng(61.858562, 0.947132),
                          LatLng(61.858458, 0.947192),
                          LatLng(61.85844, 0.947716),
                          LatLng(61.858488, 0.947819),
                          LatLng(61.858766, 0.947818),
                          LatLng(61.858893, 0.947779),
                          LatLng(61.858975, 0.947542),
                          LatLng(61.858881, 0.947234)
                        ]
                      ],
                      color: Colors.lightGreen.withOpacity(0.5),
                      borderColor: Colors.lightGreen,
                      borderStrokeWidth: 1),
                ],
              ),
            ],
          ),
```

### Do you have a potential solution?

I don't have a fix unfortunately, but it can be temporarily worked around using the alternative renderer, or by ensuring that polygons do not have the same colour (a slightly different opacity setting is enough)

### Platforms

Android 14, Windows 11, iOS 17

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

### PR DESCRIPTION
**Pull request by JaffaKetchup**
Fixes #1898.

Note that these new measures to ensure correct functionality could negatively impact performance. This is properly documented.

### CODE REVIEW

**Review by JaffaKetchup — COMMENTED** [review]
One thing I didn't check was whether the cutting issue (caused by two overlapping polygons) had been resolved, if they are both fully opaque.

Possibly I was solving one issue and not the other, maybe instead this is due to the clockwise/anticlockwise stuff.

File: lib/src/layer/polygon_layer/painter.dart [hunk 1]
```diff
@@ -209,11 +223,25 @@ base class _PolygonPainter<R extends Object>
 
         for (final holeOffsets in holeOffsetsList) {
           filledPath.addPolygon(holeOffsets, true);
+
+          /* https://github.com/flutter/flutter/issues/44572          
+          filledPath = Path.combine(
+            PathOperation.difference,
+            filledPath,
+            Path()..addPolygon(holeOffsets, true),
+          );*/
```
Comment (josxha) [inline lib/src/layer/polygon_layer/painter.dart:232]: How about a TODO with information when this can get removed or re-added? I think this would be better than regular commented out code.

**Review by josxha — APPROVED** [review]

**Comment by josxha** [comment]
I did some quick testing and all works like excepted. Good job!

File: lib/src/layer/polygon_layer/painter.dart (hunk 1 above)
Comment (JaffaKetchup) [reply lib/src/layer/polygon_layer/painter.dart:231]: Yep, I'll do this. The linked issue is of some use, but basically this code is just potentially more efficient than what we're doing - but not sure. Basically, once that issue is closed, we should test again to check the most efficient combination of things. I'll add that to the code.

Comment (josxha) [reply lib/src/layer/polygon_layer/painter.dart:231]: Sounds good! 👍
