### PR TITLE
fix: correct `PolygonLayer.useAltRenderer` renderer when `Polygon`s have multiple holes

### LINKED ISSUE #1899: [BUG] Alternative polygon renderer in 7.0 renderers multiple holes incorrectly
### What is the bug?

If a polygon contains multiple holes and the useAltRendering property is set on the polygon layer, then the holes are cut out incorrectly (with vertices from different holes seemingly connecting to each other)

**Expected output:**
Screenshot 2024-05-30 123727

**Actual output:**
Screenshot 2024-05-30 123709

### How can we reproduce it?

The following code can be used to reproduce this issue:

```dart
          FlutterMap(
            options: const MapOptions(
              initialCenter: LatLng(64.025, -1.132),
              initialZoom: 16,
            ),
            children: [
              PolygonLayer(
                useAltRendering: true,
                polygons: [
                  Polygon(
                      points: const [
                        LatLng(64.0283, -1.13083),
                        LatLng(64.0282, -1.130172),
                        LatLng(64.024794, -1.130862),
                        LatLng(64.0247, -1.13126),
                        LatLng(64.0247, -1.13183),
                        LatLng(64.025, -1.13274),
                        LatLng(64.0254, -1.13352),
                        LatLng(64.0259, -1.134093),
                        LatLng(64.027859, -1.135774),
                        LatLng(64.027915, -1.134542),
                        LatLng(64.028168, -1.132229),
                        LatLng(64.028284, -1.131658),
                        LatLng(64.0283, -1.13083)
                      ],
                      holePointsList: const [
                        [
                          LatLng(64.026675, -1.133183),
                          LatLng(64.026601, -1.133234),
                          LatLng(64.026534, -1.133158),
                          LatLng(64.026534, -1.13302),
                          LatLng(64.026601, -1.132944),
                          LatLng(64.026688, -1.13303),
                          LatLng(64.026675, -1.133183)
                        ],
                        [
                          LatLng(64.026226, -1.134005),
                          LatLng(64.0262, -1.134068),
                          LatLng(64.026149, -1.134059),
                          LatLng(64.02616, -1.133918),
                          LatLng(64.026211, -1.133933),
                          LatLng(64.026226, -1.134005)
                        ],
                        [
                          LatLng(64.025838, -1.13236),
                          LatLng(64.02578, -1.132496),
                          LatLng(64.025723, -1.132513),
                          LatLng(64.025669, -1.132476),
                          LatLng(64.025631, -1.132298),
                          LatLng(64.025695, -1.132169),
                          LatLng(64.025752, -1.132159),
                          LatLng(64.025804, -1.132202),
                          LatLng(64.025838, -1.13236)
                        ]
                      ],
                      label: "No 3",
                      color: Colors.lightBlue.withOpacity(0.5),
                      borderColor: Colors.lightBlue,
                      borderStrokeWidth: 1),
                ],
              ),
            ],
          ),
```

### Do you have a potential solution?

_No response_

### Platforms

Windows 11, iOS 17

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

### PR DESCRIPTION
**Pull request by JaffaKetchup**
Also added helpful debugging tool to show triangulation output.

Fixes #1899.

### CODE REVIEW

File: lib/src/layer/polygon_layer/polygon_layer.dart [hunk 1]
```diff
@@ -76,15 +82,17 @@ class PolygonLayer<R extends Object> extends StatefulWidget {
...
     this.polygonLabels = true,
     this.drawLabelsLast = false,
     this.hitNotifier,
-  }) : assert(
+  })  : assert(
           simplificationTolerance >= 0,
           'simplificationTolerance cannot be negative: $simplificationTolerance',
-        );
+        ),
+        debugAltRenderer = kDebugMode && debugAltRenderer;
```
Comment (josxha) [inline lib/src/layer/polygon_layer/polygon_layer.dart:95]: What is the reason that the `debugAltRenderer` gets limited to the debug mode and can't be used otherwise? It could still be useful in production with e.g. a debug/dev menu.

If users want to have it enabled just in dev mode they could use kDebugMode themselfs and have full control.

**Review by josxha — APPROVED** [review]
Nice debug overlay!

One polygon on the polygon page seems odd to me. But it is not caused by this pr because master has the same behavior.

**Comment by JaffaKetchup** [comment]
> One polygon on the polygon page seems odd to me.

It's designed to show that we don't support self-intersecting `Polygon`s. The earcutting algorithm is an extension of ear-clipping that supports holes, but it still doesn't support self-intersections.
